postgres:
  host: db
  port: 5432
  user: postgres
  password: postgres
  dbname: postgres
  timeout: 30s
kafka:
  brokers:
    - kafka:29092
  topics:
    completed: completed
    tasks: tasks
  consumer_group: group
server:
  port: 7001