postgres:
  host: db
  port: 5432
  user: postgres
  password: postgres
  dbname: postgres
  timeout: 30s
kafka:
  consumer_group: consumer-group
  kafka_addrs:
    - host: kafka
      port: 29092
      topic: tasks
server:
  port: 7001